ID_EMPTY = '00000000-0000-0000-0000-000000000000'

CLASS_TRIGGER_ON_LAUNCH_SCENE = 'StartTrigger'
CLASS_TRIGGER_KEY = 'KeyTrigger'
CLASS_TRIGGER_COLLISION = 'CollisionTrigger'
CLASS_TRIGGER_ANIMATION = 'AnimationTrigger'
CLASS_TRIGGER_STATE_MACHINE = 'StateMachineTrigger'
CLASS_TRIGGER_COMPARISON = 'CompareTrigger'
CLASS_TRIGGER_GROUP = 'GroupTrigger'
